ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_status_check;

ALTER TABLE tasks ADD CONSTRAINT tasks_status_check CHECK (status IN (
  'INBOX', 'REFINING', 'BLOCKED', 'READY', 'BUILDING', 'FAILED',
  'REVIEWING', 'CHANGES_REQUESTED', 'CI', 'PR_READY',
  'AWAITING_APPROVAL', 'MERGED', 'DEPLOYED', 'VERIFIED',
  'CANCELLED', 'ABANDONED', 'SUPERSEDED'
));
