# Generated by scripts/generate-cli-artifacts.ts
_praxrail() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "version init login logout doctor runtime profile project repo task channel approval upgrade support" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    runtime) COMPREPLY=( $(compgen -W "serve start stop restart status logs" -- "$cur") ) ;;
    profile) COMPREPLY=( $(compgen -W "list use" -- "$cur") ) ;;
    project) COMPREPLY=( $(compgen -W "create list show update archive" -- "$cur") ) ;;
    repo) COMPREPLY=( $(compgen -W "add inspect approve list show disable remove" -- "$cur") ) ;;
    task) COMPREPLY=( $(compgen -W "create list show clarify prioritize pause resume cancel retry abandon archive status watch logs events attempts costs verification findings ownership attach shell return recover diff check review fix publish pull-request" -- "$cur") ) ;;
    channel) COMPREPLY=( $(compgen -W "setup link verify status test preference rotate disable revoke" -- "$cur") ) ;;
    approval) COMPREPLY=( $(compgen -W "approve reject" -- "$cur") ) ;;
    upgrade) COMPREPLY=( $(compgen -W "preflight" -- "$cur") ) ;;
    support) COMPREPLY=( $(compgen -W "bundle" -- "$cur") ) ;;
  esac
}
complete -F _praxrail praxrail
