import { access, cp, mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const groups: Readonly<Record<string, readonly string[]>> = {
  runtime: ['serve', 'start', 'stop', 'restart', 'status', 'logs'],
  profile: ['list', 'use'],
  project: ['create', 'list', 'show', 'update', 'archive'],
  repo: ['add', 'inspect', 'approve', 'list', 'show', 'disable', 'remove'],
  task: [
    'create',
    'list',
    'show',
    'clarify',
    'prioritize',
    'pause',
    'resume',
    'cancel',
    'retry',
    'abandon',
    'archive',
    'status',
    'watch',
    'logs',
    'events',
    'attempts',
    'costs',
    'verification',
    'findings',
    'ownership',
    'attach',
    'shell',
    'return',
    'recover',
    'diff',
    'check',
    'review',
    'fix',
    'publish',
    'pull-request',
  ],
  channel: [
    'setup',
    'link',
    'verify',
    'status',
    'test',
    'preference',
    'rotate',
    'disable',
    'revoke',
  ],
  approval: ['approve', 'reject'],
  upgrade: ['preflight'],
  support: ['bundle'],
};
const rootCommands = [
  'version',
  'start',
  'stop',
  'restart',
  'status',
  'logs',
  'ask',
  'command',
  'cmd',
  'watch',
  'output',
  'shell',
  'init',
  'login',
  'logout',
  'doctor',
  ...Object.keys(groups),
];
const packageRoot = path.resolve('packages/cli');
const completionRoot = path.join(packageRoot, 'completions');
const manualRoot = path.join(packageRoot, 'man');
const runtimeRoot = path.join(packageRoot, 'runtime');
const builtRuntimeRoot = path.resolve('dist');
await mkdir(completionRoot, { recursive: true });
await mkdir(manualRoot, { recursive: true });

const bashCases = Object.entries(groups)
  .map(
    ([group, actions]) =>
      `    ${group}) COMPREPLY=( $(compgen -W "${actions.join(' ')}" -- "$cur") ) ;;`,
  )
  .join('\n');
const bash = `# Generated by scripts/generate-cli-artifacts.ts
_praxrail() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  if [[ COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${rootCommands.join(' ')}" -- "$cur") )
    return
  fi
  case "\${COMP_WORDS[1]}" in
${bashCases}
  esac
}
complete -F _praxrail praxrail
complete -F _praxrail pxr
`;

const zshGroups = Object.entries(groups)
  .map(
    ([group, actions]) =>
      `      ${group}) _values 'action' ${actions.join(' ')} ;;`,
  )
  .join('\n');
const zsh = `#compdef praxrail pxr
# Generated by scripts/generate-cli-artifacts.ts
_praxrail() {
  if (( CURRENT == 2 )); then
    _values 'command' ${rootCommands.join(' ')}
    return
  fi
  case "$words[2]" in
${zshGroups}
  esac
}
_praxrail "$@"
`;

const groupReference = Object.entries(groups)
  .map(([group, actions]) => `.TP\n.B ${group}\n${actions.join(', ')}`)
  .join('\n');
const manual = `.TH PRAXRAIL 1 "2026-07-18" "Praxrail 0.3.2" "Praxrail Manual"
.SH NAME
pxr - terminal client for the Praxrail autonomous coding runtime
.SH SYNOPSIS
.B pxr
[global options] command [arguments]
.SH DESCRIPTION
Praxrail creates, monitors, controls, verifies, reviews, and publishes coding
tasks across explicitly approved repositories. Email and Telegram provide
bounded asynchronous actions; the terminal remains authoritative.
.SH COMMANDS
${groupReference}
.SH GLOBAL OPTIONS
--profile, --json, --quiet, --no-color, --non-interactive, --timeout,
--dry-run, --yes, --follow, --version, --help.
.SH SECURITY
Repository approval, publication, revocation, and destructive task operations
require explicit confirmation. Interactive shells are available only for a
local human-owned managed workspace.
.SH SEE ALSO
https://github.com/FidelCoder/Praxrail
`;

await access(path.join(builtRuntimeRoot, 'index.js'));
await rm(runtimeRoot, { recursive: true, force: true });
await cp(builtRuntimeRoot, runtimeRoot, {
  recursive: true,
  filter: (source) => !source.endsWith('.tsbuildinfo'),
});
await Promise.all([
  writeFile(path.join(completionRoot, 'praxrail.bash'), bash, 'utf8'),
  writeFile(path.join(completionRoot, '_praxrail'), zsh, 'utf8'),
  writeFile(path.join(manualRoot, 'praxrail.1'), manual, 'utf8'),
]);
process.stdout.write(
  'Generated packaged runtime, bash/zsh completions, and praxrail(1)\n',
);
